Windows build fix for newer boost
Avoid "error C3859: virtual memory range for PCH exceeded"
error when compiling mordor on windows with boost 1.49

We already use the same argument in other vcxproj files such
as tethys and stash so this is a low risk fix.

Change-Id: Id8e8322cbb52e90cf8ead7947d3e81c093bbe296
Reviewed-on: https://gerrit.dechocorp.com/30922
Reviewed-by: Jenkins <hudsonbuild@mozy.com>
Reviewed-by: Jeremy Stanley <jeremy@mozy.com>